import React, { useState } from 'react';
import { GPUAssessmentResult } from '../types';
import { PieChart, Pie, Cell, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip } from 'recharts';
import { AlertTriangle, CheckCircle, XCircle, Thermometer, Zap, Shield, Activity, DollarSign, ExternalLink, TrendingUp, ChevronDown, ChevronUp, Cpu, ArrowLeft, Download } from 'lucide-react';

interface ResultsDashboardProps {
  data: GPUAssessmentResult;
  onReset: () => void;
  onEdit: () => void;
}

export const ResultsDashboard: React.FC<ResultsDashboardProps> = ({ data, onReset, onEdit }) => {
  const { physical, performance, report, market_analysis, grounding_urls } = data;
  const [showDetails, setShowDetails] = useState(false);

  // Safeguard: Normalize thermal score if AI returns 0-100 instead of 0-10
  const normalizedThermalScore = performance.thermal_health_score > 10 
    ? Math.round(performance.thermal_health_score / 10) 
    : performance.thermal_health_score;

  // Safeguard: Normalize Overall Score if AI returns 0-100 instead of 0-10
  const normalizedOverallScore = report.overall_score > 10 
    ? Math.round(report.overall_score / 10) 
    : report.overall_score;

  const handleDownloadReport = () => {
    const date = new Date().toLocaleDateString();
    const time = new Date().toLocaleTimeString();

    let content = `GPU VERIFICATION REPORT\n`;
    content += `Generated by GPU-Verify AI\n`;
    content += `Date: ${date} at ${time}\n`;
    content += `=============================================\n\n`;

    content += `VERDICT: ${report.verdict.toUpperCase()}\n`;
    content += `OVERALL SCORE: ${normalizedOverallScore}/10\n`;
    content += `MARKET VALUE ADJUSTMENT: ${report.market_value_adjustment > 0 ? '+' : ''}${report.market_value_adjustment}%\n\n`;

    if (market_analysis) {
      content += `MARKET ANALYSIS\n`;
      content += `---------------------------------------------\n`;
      content += `Model Identified: ${market_analysis.model_identified}\n`;
      content += `Average Price: ${market_analysis.average_price}\n`;
      content += `Price Range: ${market_analysis.price_range}\n\n`;
    }

    content += `PHYSICAL INSPECTION\n`;
    content += `---------------------------------------------\n`;
    content += `Overall Rating: ${physical.overall_physical_rating}/10\n`;
    content += `Sub-ratings:\n`;
    content += `  - Cleanliness: ${physical.sub_ratings.cleanliness}/10\n`;
    content += `  - Structural Integrity: ${physical.sub_ratings.structural_integrity}/10\n`;
    content += `  - Electrical Safety: ${physical.sub_ratings.electrical_safety}/10\n\n`;
    content += `AI Feedback:\n${physical.ai_feedback_comments}\n\n`;

    content += `PERFORMANCE & AUTHENTICITY\n`;
    content += `---------------------------------------------\n`;
    content += `Authenticity Status: ${performance.authenticity_status.toUpperCase()}\n`;
    content += `Performance Percentile: ${performance.performance_percentile}%\n`;
    content += `Thermal Health Score: ${normalizedThermalScore}/10\n\n`;
    content += `Validation Notes:\n${performance.validation_notes}\n\n`;

    if (performance.detailed_metrics && performance.detailed_metrics.length > 0) {
      content += `DETAILED TELEMETRY\n`;
      content += `---------------------------------------------\n`;
      performance.detailed_metrics.forEach(m => {
        content += `- ${m.feature.padEnd(25)}: ${m.observed.padEnd(20)} (Ref: ${m.reference}) [${m.status.toUpperCase()}]\n`;
      });
      content += `\n`;
    }

    if (grounding_urls && grounding_urls.length > 0) {
      content += `SOURCES\n`;
      content += `---------------------------------------------\n`;
      grounding_urls.forEach(url => content += `${url}\n`);
    }

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `GPU-Verify-Report-${date.replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getVerdictColor = (verdict: string) => {
    switch (verdict) {
      case "Recommend Purchase": return "text-emerald-400 border-emerald-500/50 bg-emerald-500/10";
      case "Negotiate": return "text-amber-400 border-amber-500/50 bg-amber-500/10";
      case "Avoid": return "text-rose-400 border-rose-500/50 bg-rose-500/10";
      default: return "text-slate-400";
    }
  };

  const getScoreColor = (score: number) => {
    if (score >= 8) return "text-emerald-400";
    if (score >= 5) return "text-amber-400";
    return "text-rose-400";
  };

  const getMetricStatusColor = (status: string) => {
    switch (status) {
      case "Match": return "text-emerald-400 bg-emerald-500/10 border-emerald-500/20";
      case "Deviation": return "text-amber-400 bg-amber-500/10 border-amber-500/20";
      case "Critical": return "text-rose-400 bg-rose-500/10 border-rose-500/20";
      default: return "text-slate-400 bg-slate-800 border-slate-700";
    }
  };

  const physicalChartData = [
    { name: 'Cleanliness', value: physical.sub_ratings.cleanliness },
    { name: 'Structure', value: physical.sub_ratings.structural_integrity },
    { name: 'Safety', value: physical.sub_ratings.electrical_safety },
  ];

  return (
    <div className="space-y-8 animate-in fade-in duration-700">
      
      {/* Header / Verdict */}
      <div className={`p-6 rounded-2xl border ${getVerdictColor(report.verdict)} flex flex-col lg:flex-row items-center justify-between gap-6`}>
        <div>
          <h2 className="text-3xl font-bold mb-2">Verdict: {report.verdict}</h2>
          <p className="opacity-80 max-w-xl">
            Based on the analysis, this GPU receives a final weighted score of <span className="font-bold">{normalizedOverallScore}/10</span>.
          </p>
        </div>
        
        <div className="flex flex-col sm:flex-row gap-4 w-full lg:w-auto">
          {market_analysis && (
             <div className="flex-1 lg:flex-none flex items-center gap-4 bg-slate-950/50 p-4 rounded-xl border border-slate-800">
              <TrendingUp className="w-8 h-8 text-blue-400" />
              <div>
                <div className="text-xs uppercase text-slate-500 font-bold">Market Price</div>
                <div className="text-xl font-mono font-bold text-blue-100">
                  {market_analysis.average_price}
                </div>
                <div className="text-xs text-slate-400">{market_analysis.price_range}</div>
              </div>
            </div>
          )}

          <div className="flex-1 lg:flex-none flex items-center gap-4 bg-slate-950/50 p-4 rounded-xl border border-slate-800">
            <DollarSign className="w-8 h-8 text-emerald-400" />
            <div>
              <div className="text-xs uppercase text-slate-500 font-bold">Value Adj.</div>
              <div className={`text-2xl font-mono font-bold ${report.market_value_adjustment >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                {report.market_value_adjustment > 0 ? '+' : ''}{report.market_value_adjustment}%
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* Physical Analysis Card */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl flex flex-col">
          <div className="flex items-center gap-3 mb-6 border-b border-slate-800 pb-4">
            <div className="p-2 bg-blue-500/20 rounded-lg">
              <Shield className="w-6 h-6 text-blue-400" />
            </div>
            <h3 className="text-xl font-bold">Physical Inspection</h3>
            <span className={`ml-auto text-2xl font-bold ${getScoreColor(physical.overall_physical_rating)}`}>
              {physical.overall_physical_rating}/10
            </span>
          </div>

          <div className="h-48 mb-6">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={physicalChartData} layout="vertical" margin={{ left: 40 }}>
                <XAxis type="number" domain={[0, 10]} hide />
                <YAxis dataKey="name" type="category" width={100} tick={{fill: '#94a3b8', fontSize: 12}} />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', color: '#f8fafc' }}
                  cursor={{fill: 'transparent'}}
                />
                <Bar dataKey="value" fill="#3b82f6" radius={[0, 4, 4, 0]} barSize={20} />
              </BarChart>
            </ResponsiveContainer>
          </div>

          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 flex-grow">
            <h4 className="text-sm font-semibold text-slate-400 mb-2 uppercase">AI Feedback</h4>
            <p className="text-sm text-slate-300 leading-relaxed">{physical.ai_feedback_comments}</p>
          </div>
        </div>

        {/* Performance & Auth Card */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl flex flex-col">
           <div className="flex items-center gap-3 mb-6 border-b border-slate-800 pb-4">
            <div className="p-2 bg-purple-500/20 rounded-lg">
              <Activity className="w-6 h-6 text-purple-400" />
            </div>
            <h3 className="text-xl font-bold">Performance & Auth</h3>
          </div>

          {/* Authenticity Card */}
          <div className={`mb-6 p-4 rounded-xl border flex items-center gap-4 ${
            performance.authenticity_status === 'Verified' ? 'bg-emerald-500/10 border-emerald-500/50' : 
            performance.authenticity_status === 'Fake' ? 'bg-rose-500/10 border-rose-500/50' : 
            'bg-amber-500/10 border-amber-500/50'
          }`}>
            <div className={`p-3 rounded-full shrink-0 ${
              performance.authenticity_status === 'Verified' ? 'bg-emerald-500/20 text-emerald-400' : 
              performance.authenticity_status === 'Fake' ? 'bg-rose-500/20 text-rose-400' : 
              'bg-amber-500/20 text-amber-400'
            }`}>
              {performance.authenticity_status === 'Verified' ? <CheckCircle className="w-8 h-8" /> : 
               performance.authenticity_status === 'Fake' ? <AlertTriangle className="w-8 h-8" /> : 
               <Activity className="w-8 h-8" />}
            </div>
            <div>
              <h4 className={`text-lg font-bold ${
                performance.authenticity_status === 'Verified' ? 'text-emerald-400' : 
                performance.authenticity_status === 'Fake' ? 'text-rose-400' : 
                'text-amber-400'
              }`}>
                {performance.authenticity_status === 'Verified' ? 'AUTHENTICITY VERIFIED' : 
                 performance.authenticity_status === 'Fake' ? 'FAKE GPU DETECTED' : 
                 'AUTHENTICITY WARNING'}
              </h4>
              <p className="text-xs text-slate-400 uppercase tracking-wider font-semibold">
                {performance.authenticity_status === 'Verified' ? 'Hardware Match Confirmed' : 
                 performance.authenticity_status === 'Fake' ? 'Counterfeit Hardware Identified' :
                 'Potential Hardware Mismatch'}
              </p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4 mb-6">
             <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 text-center">
                <div className="text-slate-500 text-xs uppercase font-bold mb-1">Thermal Health</div>
                <div className="flex items-center justify-center gap-2">
                  <Thermometer className="w-5 h-5 text-rose-400" />
                  <span className="text-2xl font-bold text-slate-200">{normalizedThermalScore}/10</span>
                </div>
             </div>
             <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 text-center">
                <div className="text-slate-500 text-xs uppercase font-bold mb-1">Performance %</div>
                <div className="flex items-center justify-center gap-2">
                  <Zap className="w-5 h-5 text-yellow-400" />
                  <span className="text-2xl font-bold text-slate-200">{performance.performance_percentile}%</span>
                </div>
             </div>
          </div>

          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 mb-4 flex-grow">
            <h4 className="text-sm font-semibold text-slate-400 mb-2 uppercase">Validation Notes</h4>
            <p className="text-sm text-slate-300 leading-relaxed">{performance.validation_notes}</p>
          </div>

          {performance.detailed_metrics && (
            <button 
              onClick={() => setShowDetails(!showDetails)}
              className="w-full py-3 bg-slate-800 hover:bg-slate-700 text-slate-300 text-sm font-semibold rounded-lg transition-colors flex items-center justify-center gap-2 border border-slate-700"
            >
              <Cpu className="w-4 h-4" />
              {showDetails ? "Hide Technical Telemetry" : "View Technical Telemetry"}
              {showDetails ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
            </button>
          )}
        </div>
      </div>

      {/* Expanded Details Section */}
      {showDetails && performance.detailed_metrics && (
        <div className="animate-in slide-in-from-top-4 duration-300">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl overflow-hidden">
            <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
              <Activity className="w-5 h-5 text-emerald-400" />
              Detailed Spec Comparison
            </h3>
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="border-b border-slate-800 text-slate-400 text-xs uppercase tracking-wider">
                    <th className="py-3 px-4 font-semibold">Feature / Spec</th>
                    <th className="py-3 px-4 font-semibold">Observed (Evidence)</th>
                    <th className="py-3 px-4 font-semibold">Reference (Official)</th>
                    <th className="py-3 px-4 font-semibold text-right">Status</th>
                  </tr>
                </thead>
                <tbody className="text-sm">
                  {performance.detailed_metrics.map((metric, idx) => (
                    <tr key={idx} className="border-b border-slate-800/50 hover:bg-slate-800/30 transition-colors">
                      <td className="py-3 px-4 text-slate-200 font-medium">{metric.feature}</td>
                      <td className="py-3 px-4 text-slate-300 font-mono">{metric.observed}</td>
                      <td className="py-3 px-4 text-slate-400 font-mono">{metric.reference}</td>
                      <td className="py-3 px-4 text-right">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${getMetricStatusColor(metric.status)}`}>
                          {metric.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="mt-4 text-xs text-slate-500 italic text-center">
              * Reference data sourced from public technical specifications. Observed data extracted from uploaded screenshots.
            </p>
          </div>
        </div>
      )}

      {grounding_urls && grounding_urls.length > 0 && (
        <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-4">
          <h4 className="text-sm font-bold text-slate-400 mb-3 flex items-center gap-2">
            <ExternalLink className="w-4 h-4" />
            Sources & Market Listings
          </h4>
          <div className="flex flex-wrap gap-2">
            {grounding_urls.map((url, i) => (
              <a 
                key={i} 
                href={url} 
                target="_blank" 
                rel="noreferrer"
                className="text-xs bg-slate-800 hover:bg-slate-700 text-blue-400 px-3 py-1.5 rounded-full transition-colors truncate max-w-[300px]"
              >
                {new URL(url).hostname}
              </a>
            ))}
          </div>
        </div>
      )}

      <div className="flex flex-wrap justify-center gap-4 pt-8 border-t border-slate-800">
        <button
          onClick={onEdit}
          className="flex items-center gap-2 px-6 py-3 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg font-semibold transition-all border border-slate-700 hover:border-slate-600"
        >
          <ArrowLeft className="w-4 h-4" />
          Edit Uploads
        </button>
        
        <button
          onClick={handleDownloadReport}
          className="flex items-center gap-2 px-6 py-3 bg-blue-600/20 hover:bg-blue-600/30 text-blue-300 border border-blue-500/30 rounded-lg font-semibold transition-all"
        >
          <Download className="w-4 h-4" />
          Save Report
        </button>

        <button
          onClick={onReset}
          className="flex items-center gap-2 px-8 py-3 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg font-semibold transition-all shadow-lg shadow-emerald-900/20"
        >
          Analyze Another GPU
        </button>
      </div>

    </div>
  );
};